# The Site Configuration
domain: gskie.github.io
baseurl: ""
url: https://gskie.github.io

title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!

# Build settings
#theme: minima

plugins:
  - jekyll-feed
  - jekyll-timeago

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json