domain: gskie.github.io
baseurl: /REPOSITORY-NAME/
url: "https://gskie.github.io"

title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-timeago

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md