domain: gskie.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://gskie.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: ""

title: GSkie
email: your.email@gmail.com

# many other settings
# ...

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-redirect-from
  - jekyll-timeago
  - jekyll-paginate

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - .jekyll-cache/
  - .sass-cache/
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js

timezone: Asia/Yekaterinburg

pagination: 
  enabled: true

jekyll_timeago:
  translations_path: '/lib/timeago/locales.yml'
  default_locale: 'ru'
  fallbacks: true