domain: gskie.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://gskie.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: ""

title: Your blog title
email: your.email@gmail.com

# many other settings
# ...

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-redirect-from

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - .jekyll-cache/
  - .sass-cache/

timezone: Asia/Yekaterinburg

